-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 21:32:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pqnotaburras_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pqnotaburras_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pqnotaburras_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pqnta_v2
-- -----------------------------------------------------
USE `pqnotaburras_db` ;

-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `id_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `dni` CHAR(8),
  `avatar` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(255),
  `ciudad` VARCHAR(255),
  `provincia` VARCHAR(100),
  `rol` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `fecha_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `direccion_UNIQUE` (`direccion` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(450) NOT NULL,
  `precio` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `subcategoria` VARCHAR(45) NOT NULL,
  `fotos` VARCHAR(300) NOT NULL,
  `seccion` VARCHAR(45) NULL,
  `descuento` INT(11) NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_categoria_idx` (`id_categoria` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `img1_UNIQUE` (`fotos` ASC),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC),
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pqnotaburras_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL DEFAULT 1,
  `ordenCompra` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_producto_idx` (`id_producto` ASC),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  UNIQUE INDEX `ordenCompra_UNIQUE` (`ordenCompra` ASC),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `pqnotaburras_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pqnotaburras_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`payments` (
  `id` INT(11) NOT NULL,
  `medio_de_pago` VARCHAR(45) NOT NULL,
  `tarjeta_tipo` VARCHAR(45) NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_ordenCompra` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_ordenCompra` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_ordenCompra`)
    REFERENCES `pqnotaburras_db`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pqnotaburras_db`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pqnotaburras_db`.`subcategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_categoria` VARCHAR(45) NOT NULL,
  `id_subcategoria` INT(11) NOT NULL, /*ACA VER*/
  PRIMARY KEY (`id`),
  INDEX `id_subcategoria_idx` (`id_subcategoria` ASC),
  CONSTRAINT `id_subcategoria`
    FOREIGN KEY (`id_subcategoria`)
    REFERENCES `pqnotaburras_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
